In [1]:
import numpy as np

In [2]:
vector_zeros=np.zeros(10)
vector_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
memory_size = vector_zeros.size * vector_zeros.itemsize
memory_size

80

In [4]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [9]:
vector_range = np.arange(10, 50)
vector_range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
vector_range = np.arange(10, 50)
vector_range


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
vector_reversed = vector_range[::-1]
vector_reversed

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [13]:
matrix_3x3 = np.arange(9).reshape(3, 3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
non_zero_indices = np.nonzero([1,2,0,0,4,0]) 
non_zero_indices


(array([0, 1, 4], dtype=int64),)

In [15]:
identify_matrix = np.eye(3)
identify_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
matrix_5x5 = np.zeros((5, 5)) + np.arange(5)
matrix_5x5                       

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [22]:
vector_linspace = np.linspace(0, 1, 12)[1:-1]
vector_linspace

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [23]:
random_vector = np.random.random(10)
random_vector.sort()
random_vector

array([0.08805667, 0.21265946, 0.30438123, 0.6680059 , 0.69894386,
       0.80110492, 0.91277324, 0.94178228, 0.95705223, 0.9872501 ])

In [24]:
print(np.iinfo(np.int8))
print(np.iinfo(np.int32))
print(np.iinfo(np.int64))
print(np.finfo(np.float32))
print(np.finfo(np.float64))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.40129

In [26]:
float_array = np.array([1.5, 2.6, 3.7], dtype=np.float32)
int_array = float_array.astype(np.int32)
int_array

array([1, 2, 3])

In [27]:
matrix_example = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_mean_subtracted = matrix_example - matrix_example.mean(axis=1, keepdims=True)
row_mean_subtracted

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [28]:
swap_array = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
swap_array[[0, 1]] = swap_array[[1, 0]]
swap_array

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [29]:
array = np.array([[5, 2, 3],
                  [1, 4, 6],
                  [7, 8, 9]])
n=1
sorted_indices = np.argsort(array[:, n])
sorted_array = array[sorted_indices]

In [30]:
swap_array = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
swap_array[[0, 1]] = swap_array[[1, 0]]
swap_array

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [32]:
C = np.array([1,2,3,4])
A = np.repeat(np.arange(len(C)),C)
A

array([0, 1, 1, 2, 2, 2, 3, 3, 3, 3])